server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mchtshn/spring-cloud-config-store
          username: mucahit.shn7@gmail.com
          password: mucahit29
          search-paths:
            - '*-service'
