##spring:
  ##profiles:
    ##active: EN,dev

spring:
  profiles:
    active:
      -  EN
      -  prod
      -  dog

datasource:
  username: superuser
  password: dbpassword
  jdbcurl: someurlfordb

---
spring:
  config:
    activate:
      on-profile: prod

datasource:
  username: PRODsuperuser
  password: PRODdbpassword
  jdbcurl: PRODsomeurlfordb
